# Site settings
author: Denise Pendleton-Lipinski
title: On A Quest
header-img: img/home-bg.png
email: dpendl1@hotmail.com
copyright_name: Denise Pendleton-Lipinski
description: > # this means to ignore newlines until "baseurl:"
  One woman's quest to tackle computer programming one concept at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Denise_PL
github_username:  denisepen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
