# Site settings
author: Systems Eng.
title: On A Quest
header-img: img/home-bg.png
email: dpendl1@hotmail.com
copyright_name: Systems Eng.
description: > # this means to ignore newlines until "baseurl:"
  Tackling computer programming one concept at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  denisepen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
